export type {
  Admin,
  ContactMessage,
  GalleryCollection,
  GalleryImage,
  HeroSlide,
  HomeVideo,
  Project,
  ProjectBeneficiary,
  ProjectCategory,
  ProjectDonation,
  ProjectFaq,
  ProjectImage,
  SiteSettings,
  StaticPage,
} from "@generated/client";
